version: '3'


services:
  django_web:
    container_name: django_web
    build: 
      context: .
    volumes:
      - ./apps:/apps
      - ./core:/core
      - ./locals:/locals
    ports:
      - "8000:8000"
    command: >
      python3 -m core.manage runserver 0.0.0.0:8000
