# Generated by Django 4.2.7 on 2023-11-28 09:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=10)),
                ('car_model', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='users.client')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_limit', models.DateTimeField(default=datetime.datetime(2023, 11, 29, 9, 57, 2, 834982, tzinfo=datetime.timezone.utc))),
                ('payed', models.BooleanField(default=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_places', to='parking.car')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_places', to='users.client')),
            ],
        ),
    ]
