# Generated by Django 4.2.7 on 2023-11-28 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_number',
            new_name='number',
        ),
        migrations.AlterField(
            model_name='place',
            name='date_limit',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 10, 30, 9, 674730, tzinfo=datetime.timezone.utc)),
        ),
    ]
